name: restful-api-nodejs-template # Update with the correct name
services:
    YourServiceName: # Update with the name of your service
        image: YourImageName # Update with the name of your Image
        container_name: YourContainerName # Update with the name of your container
        ports:
            - 3000:3000 # Update with the correct ports
        volumes:
            - ./src:/home/docker/restful-api-nodejs/app/src # Update with the correct path to your data
        command: unless-stopped